---
title: "R Notebook"
output: html_notebook
---

Employs hierarchical clustering.

```{r}
library(factoextra)
library(cluster)
library(tidyr)
library(readxl)

## Collate all baseline variant data into matrix
variant_data <- read_excel("C:/Users/Daniel/Documents/University/GNA5900/combined_variants.xlsx")
CNV_data <- read_excel("C:/Users/Daniel/Documents/University/GNA5900/combined_cnvs.xlsx")

combined_variants <- bind_rows(variant_data, CNV_data) %>%
  filter(!grepl("1\\.1|1\\.2|1\\.3|2\\.0|-1-1", sample)) %>%
  mutate(sample = sub("^([A-Za-z]+-[0-9]{3}).*", "\\1", sample)) %>%
  filter(plp == "Y")
  
variant_count <- combined_variants %>%
  group_by(gene, sample) %>%
  summarise(VariantCount = n(),.groups = "drop")

variant_matrix_hcluster <- variant_count %>%
  pivot_wider(
    names_from = sample,
    values_from = VariantCount,
    values_fill = 0
  )

variant_matrix_hcluster <- as.matrix(variant_matrix_hcluster[ , -1])
rownames(variant_matrix_hcluster) <- variant_count %>% distinct(gene) %>% pull(gene)

variant_matrix_hcluster <- t(variant_matrix_hcluster) %>%
  na.omit() %>%
  scale()

#variant_matrix_hcluster <- as.matrix(variant_matrix_hcluster[ , -1]) # Exclude column of gene names

## Determine linkage method
m <- c( "average", "single", "complete", "ward")
names(m) <- c( "average", "single", "complete", "ward")

# compute agglomerative coefficient
ac <- function(x) {
  agnes(variant_matrix_hcluster, method = x)$ac
}
sapply(m, ac)

## Clustering
clust <- agnes(variant_matrix_hcluster, method = "ward")

## Produce dendrogram
pltree(clust, cex = 0.6, hang = -1, main = "Dendrogram")

## Identify best number of clusters
# Gap statistic
gap_stat <- clusGap(variant_matrix_hcluster, FUN = hcut, nstart = 25, K.max = 10, B = 50)
fviz_gap_stat(gap_stat)

## Apply clusters
d <- dist(variant_matrix_hcluster, method = "euclidean")
final_clust <- hclust(d, method = "ward.D2" )
groups <- cutree(final_clust, k=2)
table(groups)

plot(final_clust, main = "Hierarchical Clustering", xlab = "", sub = "", labels = FALSE)
rect.hclust(final_clust, k = 3, border = 2:4)
```
Ward's method produces highest agglomerative coefficient for this dataset.


Performs hierarchical clustering of the later timepoint data.

```{r}
library(factoextra)
library(cluster)
library(tidyr)
library(readxl)

## Collate all baseline variant data into matrix
variant_data <- read_excel("C:/Users/Daniel/Documents/University/GNA5900/combined_variants.xlsx")
CNV_data <- read_excel("C:/Users/Daniel/Documents/University/GNA5900/combined_cnvs.xlsx")

combined_variants_prog <- bind_rows(variant_data, CNV_data) %>%
  mutate(sample = sub("^([A-Za-z]+-[0-9]{3}).*", "\\1", sample)) %>%
  filter(plp == "Y")
  
variant_count_prog <- combined_variants_prog %>%
  group_by(gene, sample) %>%
  summarise(VariantCount = n(),.groups = "drop")

variant_matrix_hcluster_prog <- variant_count_prog %>%
  pivot_wider(
    names_from = sample,
    values_from = VariantCount,
    values_fill = 0
  )

variant_matrix_hcluster_prog <- as.matrix(variant_matrix_hcluster_prog[ , -1])
rownames(variant_matrix_hcluster_prog) <- variant_count %>% distinct(gene) %>% pull(gene)

variant_matrix_hcluster_prog <- t(variant_matrix_hcluster_prog) %>%
  na.omit() %>%
  scale()

#variant_matrix_hcluster_prog <- as.matrix(variant_matrix_hcluster_prog[ , -1]) # Exclude column of gene names

## Determine linkage method
m <- c( "average", "single", "complete", "ward")
names(m) <- c( "average", "single", "complete", "ward")

#function to compute agglomerative coefficient
ac <- function(x) {
  agnes(variant_matrix_hcluster_prog, method = x)$ac
}

#calculate agglomerative coefficient for each clustering linkage method
sapply(m, ac)

## Clustering w/ Ward's method
clust <- agnes(variant_matrix_hcluster_prog, method = "ward")

#produce dendrogram
pltree(clust, cex = 0.6, hang = -1, main = "Dendrogram")

## Identify best number of clusters
# Gap statistic
gap_stat <- clusGap(variant_matrix_hcluster_prog, FUN = hcut, nstart = 25, K.max = 10, B = 50)
fviz_gap_stat(gap_stat)

## Apply clusters
d <- dist(variant_matrix_hcluster_prog, method = "euclidean")
final_clust <- hclust(d, method = "ward.D2" )
groups <- cutree(final_clust, k=2)
table(groups)

plot(final_clust, main = "Hierarchical Clustering", xlab = "", sub = "", labels = FALSE)
rect.hclust(final_clust, k = 3, border = 2:4)
```