---
title: "R Notebook"
output: html_notebook
---

---
title: "R Notebook"
output: html_notebook
---

Performs a principle component analysis of the entire data set.

```{r}
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
library(cowplot)

# Collate all baseline variant data into matrix
variant_data <- read_excel("C:/Users/Daniel/Documents/University/GNA5900/combined_variants.xlsx")
CNV_data <- read_excel("C:/Users/Daniel/Documents/University/GNA5900/combined_cnvs.xlsx")

combined_variants <- bind_rows(variant_data, CNV_data) %>%
  filter(!grepl("1\\.1|1\\.2|2\\.0|-1-1", sample)) %>%
  mutate(sample = sub("^([A-Za-z]+-[0-9]{3}).*", "\\1", sample))

variant_count <- combined_variants %>%
  group_by(gene, sample) %>%
  summarise(VariantCount = n(),.groups = "drop")

variant_matrix <- variant_count %>%
  pivot_wider(
    names_from = sample,
    values_from = VariantCount,
    values_fill = 0
  )

variant_matrix <- as.matrix(variant_matrix[ , -1])  # remove gene column
rownames(variant_matrix) <- variant_count %>% distinct(gene) %>% pull(gene)

# Transpose: samples become rows
variant_matrix <- t(variant_matrix)

#print(variant_matrix)

# Perform PCA and graph
variant_matrix <- as.matrix(variant_matrix[ , -1]) # Exclude column of gene names
PCA <- prcomp(variant_matrix, scale. = TRUE, center = TRUE)

scores <- as.data.frame(PCA$x)
scores$PMC_ID <- rownames(scores)

clinical_data <- read_excel("C:/Users/Daniel/Documents/University/GNA5900/patient_list.xlsx", sheet = 1)

pca_annotated <- scores %>%
  inner_join(clinical_data, by = "PMC_ID")
pca_annotated$cessation_number <- as.factor(pca_annotated$cessation_number)

my_colors <- c(
  "1" = "#1f77b4",
  "2" = "#FFD700",
  "3" = "#d62728"
)

plot_wide <- ggplot(pca_annotated, aes(x = PC1, y = PC2, colour = cessation_number)) +
  geom_point(size = 3) +
  scale_colour_manual(values = my_colors) +
  labs(title = "PCA of Mutation Counts") +
  theme_cowplot() + 
  theme(legend.position = "none")

plot_zoomed <- ggplot(pca_annotated, aes(x = PC1, y = PC2, colour = cessation_number)) +
  geom_point(size = 3) +
  scale_colour_manual(values = my_colors) +
  labs(title = "PCA of Mutation Counts (zoomed in)") +
  scale_x_continuous(
    limits = c(-0.5, 5.0)
  ) +
  scale_y_continuous(
    limits = c(-7.0, 4.5)
  ) +
  theme_cowplot() + 
  theme(legend.position = "none")

plot_grid(
plot_wide,
plot_zoomed
)

# How much variance is explained by this PCA?
head(PCA$sdev^2 / sum(PCA$sdev^2), 2)
```

Performs a PCA of pathways/groups of genes

```{R}
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
library(cowplot)

gene_types_raw <- read_excel("C:/Users/Daniel/Documents/University/GNA5900/variant_classes.xlsx")
gene_type_map <- gene_types_raw %>%
  pivot_longer(
    cols = everything(),
    names_to = "gene_type",
    values_to = "gene"
  ) %>%
  filter(!is.na(gene))

# Collate all baseline variant data into matrix
variant_data <- read_excel("C:/Users/Daniel/Documents/University/GNA5900/combined_variants.xlsx")
CNV_data <- read_excel("C:/Users/Daniel/Documents/University/GNA5900/combined_cnvs.xlsx")

combined_variants <- bind_rows(variant_data, CNV_data) %>%
  filter(!grepl("1\\.1|1\\.2|2\\.0|-1-1", sample)) %>%
  mutate(sample = sub("^([A-Za-z]+-[0-9]{3}).*", "\\1", sample))

combined_variants <- combined_variants %>%
  left_join(gene_type_map, by = "gene") %>%
  filter(!is.na(gene_type))

variant_count <- combined_variants %>%
  group_by(gene_type, sample) %>%
  summarise(VariantCount = n(),.groups = "drop")

variant_matrix <- variant_count %>%
  pivot_wider(
    names_from = sample,
    values_from = VariantCount,
    values_fill = 0
  )

variant_matrix <- as.matrix(variant_matrix[ , -1])  # remove gene column
rownames(variant_matrix) <- variant_count %>% distinct(gene_type) %>% pull(gene_type)

# Transpose: samples become rows
variant_matrix <- t(variant_matrix)

#print(variant_matrix)

# Perform PCA and graph
variant_matrix <- as.matrix(variant_matrix[ , -1]) # Exclude column of gene names
PCA <- prcomp(variant_matrix, scale. = TRUE, center = TRUE)

scores <- as.data.frame(PCA$x)
scores$PMC_ID <- rownames(scores)

clinical_data <- read_excel("C:/Users/Daniel/Documents/University/GNA5900/patient_list.xlsx", sheet = 1)

pca_annotated <- scores %>%
  inner_join(clinical_data, by = "PMC_ID")
pca_annotated$cessation_number <- as.factor(pca_annotated$cessation_number)

my_colors <- c(
  "1" = "#1f77b4",
  "2" = "#FFD700",
  "3" = "#d62728"
)

plot_wide <- ggplot(pca_annotated, aes(x = PC1, y = PC2, colour = cessation_number)) +
  geom_point(size = 3) +
  scale_colour_manual(values = my_colors) +
  labs(title = "PCA of Mutation Counts per Pathway") +
  theme_cowplot() + 
  theme(legend.position = "none")

# plot_zoomed <- ggplot(pca_annotated, aes(x = PC1, y = PC2, colour = cessation_number)) +
#   geom_point(size = 3) +
#   scale_colour_manual(values = my_colors) +
#   labs(title = "PCA of Mutation Counts (zoomed in)") +
#   scale_x_continuous(
#     limits = c(-0.5, 5.0)
#   ) +
#   scale_y_continuous(
#     limits = c(-7.0, 4.5)
#   ) +
#   theme_cowplot() + 
#   theme(legend.position = "none")

plot_wide

# plot_grid(
# plot_wide,
# plot_zoomed
# )

# How much variance is explained by this PCA?
head(PCA$sdev^2 / sum(PCA$sdev^2), 2)
```


Runs an ANOVA on the data from the second PCA

```{r}
print("  --=={ PC1 }==--  ")
anova_pc1 <- aov(PC1 ~ baseline_PSA, data = pca_annotated)
summary(anova_pc1)

print("  --=={ PC2 }==--  ")
anova_pc2 <- aov(PC2 ~ baseline_PSA, data = pca_annotated)
summary(anova_pc2)
```
